import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          HACKUM Клубд тавтай морил
        </h1>

        <p className={styles.description}>
          Манай Клубд нэгдэж, бидний нэг болсон танд баяр хүргэе.
        </p>

        <div className={styles.grid}>
          <a href="https://discord.gg/zdyb8JS8" className={styles.card}>
            <h2>HACKUM CLUB &rarr;</h2>
            <p>JOIN OUR DISCORD SERVER</p>
          </a>

          <a href="https://www.facebook.com/groups/hackum2020" className={styles.card}>
            <h2>2021 ЭЛСЭЛТ &rarr;</h2>
            <p>JOIN OUR FACEBOOK GROUP</p>
          </a>

          <a
            href="https://www.facebook.com/HackumClub"
            className={styles.card}
          >
            <h2>Дотоод журам &rarr;</h2>
            <p>Клубийнхээ дотоод журамтай заавал танилцаарай.</p>
          </a>

          <a
            href="https://www.facebook.com/groups/hackum"
            className={styles.card}
          >
            <h2>Нэгдсэн бүлгэмд нэгдэх &rarr;</h2>
            <p>
              wqwerasdf
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.facebook.com/groups/hackum"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
